services:
  postgresdb:
    image: 'postgres:15-alpine'
    container_name: db_postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: library_db
    ports:
      - "5444:5432"